var comics=[["Screen orientation","first-image.svg","May 11, 2019","My first post! I will be posting weekly until I get good at it, then I will try for daily."],
              ["Weebly","weebly.svg","May 24, 2019",""],
              ["British hat","british_hat.svg","May 11, 2019",""],
              ["Sandwich bar","sandwich_bar.svg","June 2,2019",""],
              ["Opinions","opinions.svg","June 9, 2019",""],
              ["Free fruit for kids","free-fruit-for-kids.svg","June 18, 2019",""],
              ["Babysitting part 1","katherine_babysitting_1.svg","June 23, 2019",""],
              ["Babysitting part 2","katherine_babysitting_2.svg","July 1, 2019","Sorry this ones late, I have been very busy recently."],
              ["Testing animated SVG images","animated.svg","July 1, 2019","Testing the use of Javascript to animate SVG images"],
              ["Fourth of July 2019!","fourth-of-july-special-2019.svg","July 7, 2019","I know its a bit late... Who posts on the 4th of July?"],
              ["Babysitting part 3","katherine_babysitting_3.svg","July 14, 2019","I know its darker than the others, the idea is that the babies are taking over the world. The next one will be better, hopefully"],
              ["Babysitting part 4","katherine_babysitting_4.svg","July 22, 2019","Sorry its late, but good news! Starting tomorrow, I will be posting <i>every day</i>!"],
              ["Florida Trip part 1","florida_trip_1.svg","July 23, 2019","The daily thing is working so far... lets hope it keeps working!"],
              ["I'm Bored","im_bored.svg","July 24, 2019","Still going daily... most of the time the posts are later at night than usual though."],
              ["Florida Trip part 2","florida_trip_2.svg","July 25, 2019","Daily isn't so hard... Yet"],
              ["Xenophobious Lovegood","xenophobious.svg","July 26, 2019","Still going daily... It certainly makes time seem to go by slower."],
              ["Florida Trip part 3","florida_trip_3.svg","July 27, 2019","Five days of daily posts... it feels like a lot more."],
              ["Florida Trip part 4","florida_trip_4.svg","July 28, 2019","My first Sunday comic since I started doing it daily!"],
              ["Hot","hot.svg","July 30, 2019","This is embarrasing... The first missed comic. I hope it won't happen again."],
              ["Phone case","phone_case.svg","July 31, 2019","Don't worry, seymour is still a main character."],
              ["Phone case part 2","phone_case_2.svg","August 1, 2019",""],
              ["Ethan","Ethan.svg","August 2, 2019","Introducing a new character..."],
              ["Barney","barney_the_stubborn_rabbit.svg","August 3, 2019",""],
              ["Walking the bunny part 1","barney_walking.svg","August 4, 2019","Life advice: never get a giant bunny."],
              ["Baking part 1","baking_cookies.svg","August 5, 2019",""],
              ["Walking the Bunny part 2","walking_the_bunnny_2.svg","August 6, 2019",""],
              ["Baking part 2","baking_for_the_party_1.svg","August 7, 2019","Sorry about the name confusion... I had forgotten about Baking part 1."],
              ["Breaking the fourth wall","breaking_the_fourth_wall.svg","August 8, 2019", "Almost at three weeks of daily comics!"],
              ["Baking part 3","baking_3.svg","August 9, 2019","If I get the dates wrong, please tell me in the comments."],
              ["Finding Barney part 1","finding_barney_1.svg","August 10, 2019","I did not miss yesterdays comic... I just posted it really late."],
              ["Snow White","snow_white.svg","August 11, 2019",""],
              ["Is that animated?","is_that_animated.svg","August 12, 2019","My first animated one since Testing Animated SVG Images!"],
              ["End of the animations (not)","end_of_the_animations_not.svg","August 13, 2019","Exciting, isn't it? I'm making animated comics a trend."],
              ["Skating","skating.svg","August 14, 2019","No animation today, it takes a long time to make them and I have a busy day."],
              ["Finding Barney part 2","finding_barney_2.svg","August 15, 2019","A long animation to make up for yesterday?"],
              ["Isaac's walk cycle (for future animations)","Isaac_walk_cycle.svg","August 16, 2019","I know its a blocky animation, but its my first one :)"],
              ["Too much action","comics_with_too_much_talking.svg","August 17, 2019","This animation is even worse, but have you ever seen the Javascript code for a two-stage SVG animation with no external API's?"],
              ["Political cartoonism","political_cartoonism.svg","August 18, 2019","Try to figure out the metaphors, its based on real problems that I'm mad about."],
              ["Sielminnar","sielminnar.svg","August 19, 2019","Sielminnar and Isaac's summoning spell <i>are</i> real Afrikaans. :)"],
              ["Florida Trip part 5","florida_trip_5.svg","August 20, 2019",""],
              ["Florida Trip part 6","florida_trip_6.svg","August 21, 2019","Was it tacky to bring back the old Florida Trip series?"],
              ["Florida Trip part 7","florida_trip_7.svg","August 22, 2019","Nigel is starting to become a main character, but I'm not getting rid of Katherine or Seymour. Also, Sally is the girl with the glasses (in the fourth of july special she was carrying a 'Canada' sign.)"],
              ["Florida Trip part 8","florida_trip_8.svg","August 23, 2019","This comic breaks a lot of my personal records. It features all of the characters, takes place in a giant panel (only used once before), and has the longest animation (twenty speech bubbles). Also, it finally clarifies everyone's names."],
              ["Florida trip part 9","florida_trip_9.svg","August 24, 2019",""],
              ["Baking part 4","baking_4.svg","August 25, 2019","To clarify, those are floating cakes."],
              ["Florida Trip part 10","florida_trip_10.svg","August 26, 2019","C'est la vie."],
              ["Florida Trip part 11","florida_trip_11.svg","August 27, 2019","Welcome to the main character docket, Sally!"],
              ["Shark Man","shark_man.svg","August 28, 2019","A new character! Again!"],
              ["Meet Harold part 1","meet_harold_1.svg","August 29, 2019","Isaac is being sarcastic at the end of the animation."],
              ["Meet Harold part 2","meet_harold_2.svg","August 30, 2019","I know this is really late (for future readers, 8:40 pm), I had a hectic day."],
              ["Florida Trip part 12","florida_trip_12.svg","August 31, 2019","Late again. (9:10). Recently I've been really busy."],
              ["Florida Trip part 13","florida_trip_13.svg","September 1, 2019","Again, sorry about the recent late comics. Its been a hectic few days."],
              ["Pier","pier.svg","September 2, 2019","The things I make poor Isaac go through..."],
              ["Pier part 2","pier_2.svg","September 3, 2019","Most of the dialogue is separate from the punch line. You have to wait about 3 seconds for the joke to conclude."],
              ["Pier part 3","pier_3.svg","September 4, 2019","Poor guy."],
              ["Sporks","sporks.svg","September 6, 2019","I can't believe I missed another one. We've been traveling a lot, thankfully now its over."],
              ["Pier part 4","pier_4.svg","September 7, 2019",`Sorry again about the missed comic the day before yesterday. I hope <a onclick="reset('last')">Sporks</a> made up for it.`],
              ["Inspiration","inspiration.svg","September 8, 2019","I'm actually starting to run out of inspiration, so if anyone has an idea for a comic please post it in the comments :)"],
              ["Smart Fridge","smart_fridge.svg","September 9, 2019","As usual, no negative connotations are to be associated with this comic. Also the most complicated animation I've ever done is coming out tomorrow, so everyone make sure to see tomorrow's!"],
              ["Your Mother jokes","your_mother_jokes.svg","September 10, 2019","I know this is a huge letdown. I animate the comics using pure JavaScript, a programming language, and I've never done anything like the comic I was going to post before. I will start working on an API which should make the complicated animations more common and reliable."],
              ["Dawn of a new era","dawn_of_a_new_era.svg","September 11, 2019","I can't guarantee that I will get that one comic I've been promising out tomorrow, I have to work on the API. More (and more complicated) animations will be coming out regularly no matter what."],
              ["Power Cord","power_cord.svg","September 12, 2019","This is the first complicated animation made with my graphics api!"],
              ["Lawn Pee","lawn_pee.svg","September 13, 2019","Some males hold the hose right there when they are watering their lawn (with a garden hose, not a human hose)."],
              ["Jump the shark (suggested by Jason)","jump_the_shark.svg","September 14, 2019","Yay! This is the first time I've posted on time in a while!"],
              ["Elephant popping","elephant_popping.svg","September 15, 2019","Sorry about yesterday's misname, it was Jason's idea to make Isaac jump over Harold."],
              ["Elephant popping part 2","elephant_popping_2.svg","September 16, 2019","This has taken place as most complicated comic, with a full walk cycle and a multi frame setup."],
              ["Computer Case","computer_case.svg","September 17, 2019","I guess you can expect my monday comics to be later as we are usually busy on those days, but the other days should mostly be on time. Sorry about all of the late comics, we have been busy recently."],
              ["Elephant popping part 3","elephant_popping_3.svg","September 18, 2019","Sorry about the time. I will also be posting late tomorrow (or maybe late tonight)."],
              ["Cheese Grater","cheese_grater.svg","September 20, 2019","Sorry about yesterday, it was the funeral of a relative."],
              ["Inflatable mattress part 1","inflatable_mattress.svg","September 21, 2019","Semi-on-time today, right? This might be the beginning of my funniest series yet."],
              ["Inflatable mattress part 2","inflatable_mattress_2.svg","September 22, 2019","Not my most complicated animation... Should these be in the Guinness book of world records?"],
              ["Inflatable mattress part 3","inflatable_mattress_3.svg","September 23, 2019",""],
              ["Inflatable mattress part 4","inflatable_mattress_4.svg","September 24, 2019","A little darker than my other comics, but it's literally 9 PM at the time of writing."],
              ["Feeding Time","feeding_time.svg","September 25, 2019","A funny to make up for yesterday?"],
              ["Mr. Shark","mr_shark.svg","September 26, 2019","Sorry its late, I had some computer troubles (My battery percentage goes from 60 to 0 in 5 seconds)"],
              ["Whatcha Wanna Do?","whatcha_wanna_do.svg","September 27, 2019","Wow... The entire month of September is almost over! I guess time flies when your an animator."],
              ["Theology","theology.svg","September 28, 2019",""],
              ["Planet Earth","planet_earth.svg","September 29, 2019","Sorry about the late comic. (I'm a bit absent minded, can you tell?)"],
              ["Phone","phone.svg","September 30, 2019","Does anyone get yesterday's comic?"],
              ["Big Oil","gunner.svg","October 1, 2019","Singles like this will probably get more common. (If you mouse over the image, you'll see the file name is 'gunner.svg')"],
              ["Save The Orangutans","palm_oil.svg","October 2, 2019","Cutting down palm trees in those regions is causing orangutans to go nearly exstinct, as they are forced out of the forest and the greedy ****'s that cut down the trees in the first place just shoot them. More information <a href='https://www.worldwildlife.org/magazine/issues/summer-2015/articles/orangutans-and-palm-oil-protecting-forests-to-help-great-apes'>here</a>."],
              ["Identical Twins","identical_twins.svg","October 3, 2019","Of course I had to make him a twin <i>eventually</i>"],
              ["Who's That","whos_that.svg","October 4, 2019","Twins can pull a lot of funny pranks"],
              ["Palm Oil 2","palm_oil_2.svg","October 5, 2019","As you can tell, I like Nigel a lot more than Geoffrey. Don't be like Geoffrey."],
              ["Candy Wrapper","plastic.svg","October 6, 2019",""],
              ["Sushi Bar","sushi_bar.svg","October 7, 2019","Sorry about the time, again. I was sapped of ideas."],
              ["Lunch","breakfast.svg","October 8, 2019","Remember, global warming is real. Do the research if you don't think so. "],
              ["Sarah","sarah.svg","October 9, 2019","Wow! 88 comics!"],
              ["Macrosomia","macrosomia.svg","October 10, 2019","Not as funny as usual. If you are a daily reader then you know this one was really, really late."],
              ["Politicians cruiser","politician_cruiser.svg","October 12, 2019","I know I missed posting yesterday. I guess its time for the big reveal... We were on vacation sporadically through september and October. We left Cocoa Beach yesterday! We got home late (we live in central Atlanta, so the trip was pretty long), and I wasn't able to get a comic made."],
              ["Pumpkin","pumpkin.svg","October 13, 2019","Halloween is almost here! I'll make a real comic tomorrow."],
              ["First Steps","first_steps.svg","October 14, 2019","I <i>didn't</i> miss yesterday's comic, it just didn't publish right (Alright, I forgot to push a button.)"],
              ["You've got to be kidding me","youve_got_to_be_kidding_me.svg","October 15, 2019","Not my most inspired work. At the time of writing it is 9:20 pm."],
              ["Insane","insane.svg","October 16, 2019","Tis the season to be insane!"],
              ["Insane part 2","insane_2.svg","October 17, 2019",""],
              ["Insane part 3","insane_3.svg","October 18, 2019","Halloween is getting close!"],
              ["Insane part 4","insane_4.svg","October 19, 2019","I know this joke is getting old. Also an important bulletin, my comic will be late Monday and Tuesday. Tuesday will be my hundreth comic!"],
              ["White Tablecloth","white_tablecloth.svg","October 20, 2019","I know, everyone wants another walk cycle (or at least I think you do). Its not easy to do walk cycles, even with my new API."],
              ["Nerd","nerd.svg","October 21, 2019","It's been like eighty day's since I published one thats not animated. I will probably do an animated every other day, and a regular one in the gaps. (By the way, Seymour is <i>not</i> taller than Isaac. All of them, with a few exceptions for Ethan, Sarah, and the infants, are the same height)."],
              ["Stevenson","stevenson.svg","October 22, 2019","No offense intended to people with chronic depression. Also, this is my ONE HUNDRETH COMIC!!!"],
              ["Nobel prize","questionairre.svg","October 23, 2019","I know the title doesn't really describe the comic. I figured '100,000 volts' wasn't very good.'"],
              ["Sally's apartment","internet.svg","October 24, 2019","(Stevenson has a crush on Sally)"],
              ["Weather forecaster","weather_forecaster.svg","October 25, 2019","Should I start making a comic book containing these <i>now</i> or later?"],
              ["Hey, I'm...","scared_stevenson.svg","October 26, 2019","Not a masterpiece..."],
              ["Self Discovery part 1","self_discovery_1.svg","October 30, 2019","Sorry about the missed comics. My computer broke, and I can't use any other for the comic."],
              ["2019 Halloween Special 1","2019_halloween_special_1.svg","October 31, 2019","This is the first of several comics I will post today. I've been planning this one for several months."],
              ["Self Discovery part 2","self_discover_2.svg","November 1, 2019",""],
              ["Self Discovery part 3","self_discovery_3.svg","November 2, 2019","More self discovery! (P.S: I don't recommend his method)."],
              ["Self Discovery part 4","self_discovery_4.svg.svg","November 3, 2019","Finally! An animated one! Its been almost... wow... <i>3 days!</i>"],
              ["Self Discovery part 5","self_discovery_5.svg","November 4, 2019","Some fast food places (maybe not McDonalds) have ketchup fountains."],
              ["Secret","secret.svg","November 5, 2019","Quick tip: Always wait for the time it would take for one speech bubble to turn on and off after an animation. I never make the punch line wait later than that."],
              ["The Metropolis Post - Edition 1","metropost_1.svg","November 6, 2019","A little different this time, eh? I will probably post one of these weekly. (Its all satirical comedy, except for the bottom part. I will probably include real world news in the bottom part."],
              ["Barneys job","lawyer.svg","November 8, 2019","Sorry about the missed yesterday. We have a kinda slow tech guy... The computer issues of a few days ago came back to haunt me. You know what they say: Fix it until it breaks, then fix it some more."],
              ["The Metropolis Post - Edition 2","metropost_2.svg","November 9, 2019","I didn't have any other ideas today. The next one will be in exactly one week."],
              ["A good plot","book.svg","November 10, 2019","I almost skipped this one. After being unable to use my computer for several days, I lost my normal routine. Hopefully I will start posting on time."],
              ["Barneys job part 2","barneys_job_2.svg","November 11, 2019","I guess if I post every night, its like getting it really early the next day."],
              ["Isaac's Piano part 1","isaacs_piano_1.svg","November 12, 2019","Sorry about the timing confusion I had. Its hard to explain..."],
              ["Rad","rad.svg","November 13, 2019","Change of pace, eh? Don't worry, I will post more Isaac's Piano tomorrow. This is a random drawing I scrapped up from my desk drawer :)"],
              ["Isaac's Piano part 2","isaacs_piano_2.svg","November 14, 2019","Different comic style this time. My comic has been changing a lot recently."],
              ["Isaac's Piano part 3","isaacs_piano_3.svg","November 15, 2019","Hmm... I thought I had such a good idea for today. It could be that I made this while watching a depressing superhero movie."],
              ["Iceberg part 1","iceberg.svg","November 16, 2019","Don't worry... I haven't scrapped Isaac's Piano."],
              ["The Metropolis Post - Edition 3","metropost_3.svg","November 17, 2019","Every sunday! (Or early monday)"],
              ["Iceberg part 2","iceberg_2.svg","November 18, 2019","These are just fillers. Don't worry... Isaacs piano comes into this eventually."],
              ["Iceberg part 3","iceberg_3.svg","November 19, 2019","8 days to thanksgiving!"],
              ["Sheeple","sheeple.svg","November 20, 2019","Yes, I am calling anyone who <em>STILL</em> thinks global warming is a myth a sheeple."],
              ["Iceberg part 4","iceberg_4.svg","November 21, 2019","The extra guy is Isaac's twin brother, who I haven't run for a very long time."],
              ["Iceberg part 5","iceberg_5.svg","November 22, 2019","Someone remind me to make a Thanksgiving 2019 series before its too late..."],
              ["Thanksgiving 2019 part 1","thanksgiving_2019_1.svg","November 23, 2019","I probably won't do an animated one for some time."],
              ["Thanksgiving 2019 part 2","thanksgiving_2019_2.svg","November 24, 2019","This is turning into a theme."],
              ["Thanksgiving 2019 part 3","thanksgiving_2019_3.svg","November 25, 2019","I suppose the Thanksgiving 2019 series is just a compilation of misadventures."],
              ["Thanksgiving 2019 part 4","thanksgiving_2019_4.svg","November 26, 2019","The piano!"],
              ["Iceberg part 6","iceberg_6.svg","November 27, 2019","More iceberg! I guess <i>animated</i> comics will soon be rare, instead of the vice versa."],
              ["Iceberg part 7","iceberg_7.svg","November 30, 3019","Its almost Christmas! I guess it's time to deck out my comic with Christmas scenes"],
              ["Christmas present","christmas_present.svg","December 1, 2019","A present! The first christmas image!"],
              ["Iceberg part 8", "iceberg_8.svg","December 3, 2019","The advent calendar is coming soon!"],
              ["Iceberg part 9", "iceberg_9.svg","December 4, 2019","This is <strong>not</strong> a copy of the Inflatable Mattress series."],
              ["Iceberg part 10","iceberg_10.svg","December 5, 2019","Eventually the advent calendar will be finished. At the time of writing, I have made 6 of the ornaments! (Lots of detail)"],
              ["Iceberg part 11","iceberg_11.svg","December 6, 2019","Sorry for the unfinished comic yesterday. I guess I got absent minded?"],
              ["Stu Brunswickson part 1","stu_brunswickson_1.svg","December 8, 2019","Ouch."],
              ["Advent Calendar","advent_calendar.svg","December 9, 2019","The long awaited advent calendar! Until the 25th, I will probably post <i>behind</i> the calendar, so you have to go back one to see the recent comics. New ornaments pop up every day."]
             ];
// We nerds are really cool. Do you like Shark Week?
