{
    "comics":[
        ["Screen orientation","first-image.svg","May 11, 2019","My first post! I will be posting weekly until I get good at it, then I will try for daily.","Isaac attempts to fix the screen orientation on his computer"],
        ["Weebly","weebly.svg","May 24, 2019","","Katherine shows Isaac her weebly site"],
        ["British hat","british_hat.svg","May 11, 2019","","Isaac jokes about Seymour's bearskin hat"],
        ["Sandwich bar","sandwich_bar.svg","June 2,2019","","Isaac politely asks Seymour for a sandwich"],
        ["Opinions","opinions.svg","June 9, 2019","","Nigel, Geoffrey, Sally, and Tara argue about opinions"],
        ["Free fruit for kids","free-fruit-for-kids.svg","June 18, 2019","","Isaac and Seymour find out a new way to get free fruit"],
        ["Babysitting part 1","katherine_babysitting_1.svg","June 23, 2019","","The infants that Katherine babysits answer a phone call from Isaac"],
        ["Babysitting part 2","katherine_babysitting_2.svg","July 1, 2019","Sorry this ones late, I have been very busy recently.","Katherine has a disturbing answer to Isaac's phone call"],
        ["Testing animated SVG images","animated.svg","July 1, 2019","Testing the use of Javascript to animate SVG images","My testing arena for animations"],
        ["Fourth of July 2019!","fourth-of-july-special-2019.svg","July 7, 2019","I know its a bit late... Who posts on the 4th of July?","Linuxrocks2000 celebrates the fourth of july"],
        ["Babysitting part 3","katherine_babysitting_3.svg","July 14, 2019","I know its darker than the others, the idea is that the babies are taking over the world. The next one will be better, hopefully","Katherine stumbles into Isaac's apartment in the middle of the night"],
        ["Babysitting part 4","katherine_babysitting_4.svg","July 22, 2019","Sorry its late, but good news! Starting tomorrow, I will be posting <i>every day</i>!","The last babysitting comic, in which the entire series is explained"],
        ["Florida Trip part 1","florida_trip_1.svg","July 23, 2019","The daily thing is working so far... lets hope it keeps working!","Katherine annoys Isaac about the impending trip to Florida"],
        ["I'm Bored","im_bored.svg","July 24, 2019","Still going daily... most of the time the posts are later at night than usual though.","Isaac friends figure out a new way to play Isaac's custom built gaming console"],
        ["Florida Trip part 2","florida_trip_2.svg","July 25, 2019","Daily isn't so hard... Yet","Seymour has timing issues"],
        ["Xenophobious Lovegood","xenophobious.svg","July 26, 2019","Still going daily... It certainly makes time seem to go by slower.","Isaac meets an extreme xenophobe"],
        ["Florida Trip part 3","florida_trip_3.svg","July 27, 2019","Five days of daily posts... it feels like a lot more.","Katherine drives Isaac insane with her Florida Trip preparations"],
        ["Florida Trip part 4","florida_trip_4.svg","July 28, 2019","My first Sunday comic since I started doing it daily!","Isaac accidentally yells at Nigel"],
        ["Hot","hot.svg","July 30, 2019","This is embarrasing... The first missed comic. I hope it won't happen again.","Isaac launches into a string of double entendres after Katherine makes a comment about the temperature"],
        ["Phone case","phone_case.svg","July 31, 2019","Don't worry, seymour is still a main character.","Isaac looks at a new phone case to buy"],
        ["Phone case part 2","phone_case_2.svg","August 1, 2019","","Isaac looks at another phone case"],
        ["Ethan","Ethan.svg","August 2, 2019","Introducing a new character...","We introduce Ethan, the imbalanced 12-year-old (Seymour and Isaac are each 16)"],
        ["Barney","barney_the_stubborn_rabbit.svg","August 3, 2019","","Isaac walks his giant bunny"],
        ["Walking the bunny part 1","barney_walking.svg","August 4, 2019","Life advice: never get a giant bunny.","The start of Isaac's giant bunny escapades"],
        ["Baking part 1","baking_cookies.svg","August 5, 2019","","Isaac bakes cookies"],
        ["Walking the Bunny part 2","walking_the_bunnny_2.svg","August 6, 2019","","Isaac's giant bunny walks Isaac"],
        ["Baking part 2","baking_for_the_party_1.svg","August 7, 2019","Sorry about the name confusion... I had forgotten about Baking part 1.","Isaac is asked to bake cakes for Katherines party"],
        ["Breaking the fourth wall","breaking_the_fourth_wall.svg","August 8, 2019", "Almost at three weeks of daily comics!","Seymour hypocritically breaks the fourth wall"],
        ["Baking part 3","baking_3.svg","August 9, 2019","If I get the dates wrong, please tell me in the comments.","Isaac fails to bake cakes"],
        ["Finding Barney part 1","finding_barney_1.svg","August 10, 2019","I did not miss yesterdays comic... I just posted it really late.","Barney runs away"],
        ["Snow White","snow_white.svg","August 11, 2019","","Isaac asks Seymour, Katherine, Geoffrey, and Nigel respectively about the true moral of Snow White"],
        ["Is that animated?","is_that_animated.svg","August 12, 2019","My first animated one since Testing Animated SVG Images!","Animated Blob yells at Isaac and Seymour"],
        ["End of the animations (not)","end_of_the_animations_not.svg","August 13, 2019","Exciting, isn't it? I'm making animated comics a trend.","The supposed end of all animations in the comic (not)"],
        ["Skating","skating.svg","August 14, 2019","No animation today, it takes a long time to make them and I have a busy day.","Isaac talks about skating"],
        ["Finding Barney part 2","finding_barney_2.svg","August 15, 2019","A long animation to make up for yesterday?","Barney craps out the downtown area"],
        ["Isaac's walk cycle (for future animations)","Isaac_walk_cycle.svg","August 16, 2019","I know its a blocky animation, but its my first one :)","I demonstrate the walk cycle for Isaac. Similar cycles are used over the entire comic"],
        ["Too much action","comics_with_too_much_talking.svg","August 17, 2019","This animation is even worse, but have you ever seen the Javascript code for a two-stage SVG animation with no external API's?","Isaac and Seymour talk about comic strips"],
        ["Political cartoonism","political_cartoonism.svg","August 18, 2019","Try to figure out the metaphors, its based on real problems that I'm mad about.","Isaac demonstrates his disturbing political cartoons"],
        ["Sielminnar","sielminnar.svg","August 19, 2019","Sielminnar and Isaac's summoning spell <i>are</i> real Afrikaans. :)","Katherine (hair doesn't render on some browsers) and Seymour listen in to Isaac's apartment"],
        ["Florida Trip part 5","florida_trip_5.svg","August 20, 2019","","Katherine (hair doesn't render on some browsers) ruins Isaac's enthusiasm for the Florida Trip"],
        ["Florida Trip part 6","florida_trip_6.svg","August 21, 2019","Was it tacky to bring back the old Florida Trip series?","Isaac and Seymour combat Katherines historical ideas"],
        ["Florida Trip part 7","florida_trip_7.svg","August 22, 2019","Nigel is starting to become a main character, but I'm not getting rid of Katherine or Seymour. Also, Sally is the girl with the glasses (in the fourth of july special she was carrying a 'Canada' sign.)","Isaac and Nigel decide to cause a democratic vote"],
        ["Florida Trip part 8","florida_trip_8.svg","August 23, 2019","This comic breaks a lot of my personal records. It features all of the characters, takes place in a giant panel (only used once before), and has the longest animation (twenty speech bubbles). Also, it finally clarifies everyone's names.","The LinuxRocks2000 characters democratically solve the Florida Trip issue"],
        ["Florida trip part 9","florida_trip_9.svg","August 24, 2019","","Seymour is incapable of paying attention"],
        ["Baking part 4","baking_4.svg","August 25, 2019","To clarify, those are floating cakes.","Isaac fails to bake cake"],
        ["Florida Trip part 10","florida_trip_10.svg","August 26, 2019","C'est la vie.","Katherine starts to regret her decision"],
        ["Florida Trip part 11","florida_trip_11.svg","August 27, 2019","Welcome to the main character docket, Sally!","Sally also begins to regret her decision"],
        ["Shark Man","shark_man.svg","August 28, 2019","A new character! Again!","We introduce Harold"],
        ["Meet Harold part 1","meet_harold_1.svg","August 29, 2019","Isaac is being sarcastic at the end of the animation.","Bill instantly gets along with Harold"],
        ["Meet Harold part 2","meet_harold_2.svg","August 30, 2019","I know this is really late (for future readers, 8:40 pm), I had a hectic day.","Sally is in denial of Harolds existence"],
        ["Florida Trip part 12","florida_trip_12.svg","August 31, 2019","Late again. (9:10). Recently I've been really busy.","Isaac worries about not being able to bring Barney to the condo"],
        ["Florida Trip part 13","florida_trip_13.svg","September 1, 2019","Again, sorry about the recent late comics. Its been a hectic few days.","Isaac explains why Harold can't come on the Florida Trip"],
        ["Pier","pier.svg","September 2, 2019","The things I make poor Isaac go through...","Isaac holds up a pier"],
        ["Pier part 2","pier_2.svg","September 3, 2019","Most of the dialogue is separate from the punch line. You have to wait about 3 seconds for the joke to conclude.","Isaac continues to hold up the pier"],
        ["Pier part 3","pier_3.svg","September 4, 2019","Poor guy.","Isaac and Seymour get in trouble with a policeman"],
        ["Sporks","sporks.svg","September 6, 2019","I can't believe I missed another one. We've been traveling a lot, thankfully now its over.","All the spoons in Katherines rebel against her"],
        ["Pier part 4","pier_4.svg","September 7, 2019","Sorry again about the missed comic the day before yesterday. I hope <a onclick='reset(`last`)'>Sporks</a> made up for it.","Isaac continues holding up the pier some more"],
        ["Inspiration","inspiration.svg","September 8, 2019","I'm actually starting to run out of inspiration, so if anyone has an idea for a comic please post it in the comments :)","Isaac runs out of inspiration"],
        ["Smart Fridge","smart_fridge.svg","September 9, 2019","As usual, no negative connotations are to be associated with this comic. Also the most complicated animation I've ever done is coming out tomorrow, so everyone make sure to see tomorrow's!","Isaac's annoying smart fridge rebels against him"],
        ["Your Mother jokes","your_mother_jokes.svg","September 10, 2019","I know this is a huge letdown. I animate the comics using pure JavaScript, a programming language, and I've never done anything like the comic I was going to post before. I will start working on an API which should make the complicated animations more common and reliable.","Seymour makes a your mother joke"],
        ["Dawn of a new era","dawn_of_a_new_era.svg","September 11, 2019","I can't guarantee that I will get that one comic I've been promising out tomorrow, I have to work on the API. More (and more complicated) animations will be coming out regularly no matter what.","The literal dawn of a new era in my comic"],
        ["Power Cord","power_cord.svg","September 12, 2019","This is the first complicated animation made with my graphics api!","Katherine and Seymour listen in on Isaac's apartment"],
        ["Lawn Pee","lawn_pee.svg","September 13, 2019","Some males hold the hose right there when they are watering their lawn (with a garden hose, not a human hose).","Katherine yells at Isaac for watering his mom's lawn"],
        ["Jump the shark (suggested by Jason)","jump_the_shark.svg","September 14, 2019","Yay! This is the first time I've posted on time in a while!","Isaac jumps the shark, as a reference to Fonzie doing the same"],
        ["Elephant popping","elephant_popping.svg","September 15, 2019","Sorry about yesterday's misname, it was Jason's idea to make Isaac jump over Harold.","Isaac introduces the noble art of popping elephants"],
        ["Elephant popping part 2","elephant_popping_2.svg","September 16, 2019","This has taken place as most complicated comic, with a full walk cycle and a multi frame setup.","Isaac pops elephants at an Elephant Protection Society meeting"],
        ["Computer Case","computer_case.svg","September 17, 2019","I guess you can expect my monday comics to be later as we are usually busy on those days, but the other days should mostly be on time. Sorry about all of the late comics, we have been busy recently.","Isaac puts his computer case on a diet"],
        ["Elephant popping part 3","elephant_popping_3.svg","September 18, 2019","Sorry about the time. I will also be posting late tomorrow (or maybe late tonight).","Isaac runs from a giant rabbit"],
        ["Cheese Grater","cheese_grater.svg","September 20, 2019","","Seymour demonstrates a new cheese grater"],
        ["Inflatable mattress part 1","inflatable_mattress.svg","September 21, 2019","Semi-on-time today, right? This might be the beginning of my funniest series yet.","Isaac, Katherine, and Seymour prepare to ride on an inflatable mattress"],
        ["Inflatable mattress part 2","inflatable_mattress_2.svg","September 22, 2019","Not my most complicated animation... Should these be in the Guinness book of world records?","Isaac, Katherine, and Seymour encounter a large water spout"],
        ["Inflatable mattress part 3","inflatable_mattress_3.svg","September 23, 2019","","Isaac, Katherine, and Seymour get sucked up into the water spout"],
        ["Inflatable mattress part 4","inflatable_mattress_4.svg","September 24, 2019","A little darker than my other comics, but it's literally 9 PM at the time of writing.","They lose all of their pretzels"],
        ["Feeding Time","feeding_time.svg","September 25, 2019","A funny to make up for yesterday?","A manta ray yells at Isaac"],
        ["Mr. Shark","mr_shark.svg","September 26, 2019","Sorry its late, I had some computer troubles (My battery percentage goes from 60 to 0 in 5 seconds)","A helicopter questions a shark about a missing person"],
        ["Whatcha Wanna Do?","whatcha_wanna_do.svg","September 27, 2019","Wow... The entire month of September is almost over! I guess time flies when your an animator.","Seymour, Katherine, Isaac, and Nigel (respectively) debate on what to do"],
        ["Theology","theology.svg","September 28, 2019","","Isaac writes a book on theology"],
        ["Planet Earth","planet_earth.svg","September 29, 2019","Sorry about the late comic. (I'm a bit absent minded, can you tell?)","A beautiful new road sign"],
        ["Phone","phone.svg","September 30, 2019","Does anyone get yesterday's comic?","Isaac's phone gets stolen"],
        ["Big Oil","gunner.svg","October 1, 2019","Singles like this will probably get more common. (If you mouse over the image, you'll see the file name is 'gunner.svg')","Big Oil (represented by Ethan) guns down Planet Earth with a machine gun"],
        ["Save The Orangutans","palm_oil.svg","October 2, 2019","Cutting down palm trees in those regions is causing orangutans to go nearly exstinct, as they are forced out of the forest and the greedy ****'s that cut down the trees in the first place just shoot them. More information <a href='https://www.worldwildlife.org/magazine/issues/summer-2015/articles/orangutans-and-palm-oil-protecting-forests-to-help-great-apes'>here</a>.","Nigel gets angry at Geoffrey"],
        ["Identical Twins","identical_twins.svg","October 3, 2019","Of course I had to make him a twin <i>eventually</i>","Isaac meets his identical twin"],
        ["Who's That","whos_that.svg","October 4, 2019","Twins can pull a lot of funny pranks","Isaac and Isaac play a prank on Katherine"],
        ["Palm Oil 2","palm_oil_2.svg","October 5, 2019","As you can tell, I like Nigel a lot more than Geoffrey. Don't be like Geoffrey.","Geoffrey kills orangutans and gets punched in the face"],
        ["Candy Wrapper","plastic.svg","October 6, 2019","","Bill gets yelled at by Isaac"],
        ["Sushi Bar","sushi_bar.svg","October 7, 2019","Sorry about the time, again. I was sapped of ideas.","Workers at a sushi bar try to make Harold into sushi"],
        ["Lunch","breakfast.svg","October 8, 2019","Remember, global warming is real. Do the research if you don't think so. ","Isaac, Katherine, Seymour, and Nigel go out to lunch"],
        ["Sarah","sarah.svg","October 9, 2019","Wow! 88 comics!","We introduce Sarah"],
        ["Macrosomia","macrosomia.svg","October 10, 2019","Not as funny as usual. If you are a daily reader then you know this one was really, really late.","Katherine meets Sarah"],
        ["Politicians cruiser","politician_cruiser.svg","October 12, 2019","I know I missed posting yesterday. I guess its time for the big reveal... We were on vacation sporadically through september and October. We left Cocoa Beach yesterday! We got home late (we live in central Atlanta, so the trip was pretty long), and I wasn't able to get a comic made.","Politicians get shipped off to venus"],
        ["Pumpkin","pumpkin.svg","October 13, 2019","Halloween is almost here! I'll make a real comic tomorrow.","An animated image of a jack-o-lantern"],
        ["First Steps","first_steps.svg","October 14, 2019","I <i>didn't</i> miss yesterday's comic, it just didn't publish right (Alright, I forgot to push a button.)","Sarah's first steps"],
        ["You've got to be kidding me","youve_got_to_be_kidding_me.svg","October 15, 2019","Not my most inspired work. At the time of writing it is 9:20 pm.","Isaac complains to Katherine that they 'don't have an act'"],
        ["Insane","insane.svg","October 16, 2019","Tis the season to be insane!","Isaac goes insane"],
        ["Insane part 2","insane_2.svg","October 17, 2019","","Isaac talks to his friend the tree"],
        ["Insane part 3","insane_3.svg","October 18, 2019","Halloween is getting close!","Isaac gets a neuroexamination"],
        ["Insane part 4","insane_4.svg","October 19, 2019","I know this joke is getting old. Also an important bulletin, my comic will be late Monday and Tuesday. Tuesday will be my hundreth comic!","The end of the Insane series"],
        ["White Tablecloth","white_tablecloth.svg","October 20, 2019","I know, everyone wants another walk cycle (or at least I think you do). Its not easy to do walk cycles, even with my new API.","Isaac buys a painting made by Giovanni Alfrego"],
        ["Nerd","nerd.svg","October 21, 2019","It's been like eighty day's since I published one thats not animated. I will probably do an animated every other day, and a regular one in the gaps. (By the way, Seymour is <i>not</i> taller than Isaac. All of them, with a few exceptions for Ethan, Sarah, and the infants, are the same height).","Isaac calls everyone a nerd"],
        ["Stevenson","stevenson.svg","October 22, 2019","No offense intended to people with chronic depression. Also, this is my ONE HUNDRETH COMIC!!!","We introduce Stevenson, the invisible man with chronic depression"],
        ["Nobel prize","questionairre.svg","October 23, 2019","I know the title doesn't really describe the comic. I figured '100,000 volts' wasn't very good.'","Stevenson meets Sally"],
        ["Sally's apartment","internet.svg","October 24, 2019","(Stevenson has a crush on Sally)","Stevenson hangs around Sallies apartment"],
        ["Weather forecaster","weather_forecaster.svg","October 25, 2019","Should I start making a comic book containing these <i>now</i> or later?","Isaac and Seymour argue about weather forecasters"],
        ["Hey, I'm...","scared_stevenson.svg","October 26, 2019","Not a masterpiece...","Stevenson accidentally scares Nigel and Tara"],
        ["Self Discovery part 1","self_discovery_1.svg","October 30, 2019","Sorry about the missed comics. My computer broke, and I can't use any other for the comic.","Isaac tells Katherine about his trip of self discovery"],
        ["2019 Halloween Special 1","2019_halloween_special_1.svg","October 31, 2019","This is the first of several comics I will post today. I've been planning this one for several months.","The 2019 halloween special"],
        ["Self Discovery part 2","self_discover_2.svg","November 1, 2019","","Seymour recommends a place for Isaac's trip of self discovery"],
        ["Self Discovery part 3","self_discovery_3.svg","November 2, 2019","More self discovery! (P.S: I don't recommend his method).","Isaac treks past a cactus in the desert"],
        ["Self Discovery part 4","self_discovery_4.svg.svg","November 3, 2019","Finally! An animated one! Its been almost... wow... <i>3 days!</i>","Isaac meets an Alien"],
        ["Self Discovery part 5","self_discovery_5.svg","November 4, 2019","Some fast food places (maybe not McDonalds) have ketchup fountains.",""],
        ["Secret","secret.svg","November 5, 2019","Quick tip: Always wait for the time it would take for one speech bubble to turn on and off after an animation. I never make the punch line wait later than that.","Isaac fails to tell Seymour a secret"],
        ["The Metropolis Post - Edition 1","metropost_1.svg","November 6, 2019","A little different this time, eh? I will probably post one of these weekly. (Its all satirical comedy, except for the bottom part. I will probably include real world news in the bottom part.","The first of The Metropolis Post, a fake news syndication"],
        ["Barneys job","lawyer.svg","November 8, 2019","Sorry about the missed yesterday. We have a kinda slow tech guy... The computer issues of a few days ago came back to haunt me. You know what they say: Fix it until it breaks, then fix it some more.","Barney the giant bunny gets a job"],
        ["The Metropolis Post - Edition 2","metropost_2.svg","November 9, 2019","I didn't have any other ideas today. The next one will be in exactly one week.","The second weekly edition of The Metropolis Post"],
        ["A good plot","book.svg","November 10, 2019","I almost skipped this one. After being unable to use my computer for several days, I lost my normal routine. Hopefully I will start posting on time.","Isaac writes a book"],
        ["Barneys job part 2","barneys_job_2.svg","November 11, 2019","I guess if I post every night, its like getting it really early the next day.","Barney tries a new job"],
        ["Isaac's Piano part 1","isaacs_piano_1.svg","November 12, 2019","Sorry about the timing confusion I had. Its hard to explain...","Isaac shows Seymour his new piano"],
        ["Rad","rad.svg","November 13, 2019","Change of pace, eh? Don't worry, I will post more Isaac's Piano tomorrow. This is a random drawing I scrapped up from my desk drawer :)","A random drawing I made"],
        ["Isaac's Piano part 2","isaacs_piano_2.svg","November 14, 2019","Different comic style this time. My comic has been changing a lot recently.","Katherine sees Isaacs piano"],
        ["Isaac's Piano part 3","isaacs_piano_3.svg","November 15, 2019","Hmm... I thought I had such a good idea for today. It could be that I made this while watching a depressing superhero movie.","Isaac builds a house using his piano"],
        ["Iceberg part 1","iceberg.svg","November 16, 2019","Don't worry... I haven't scrapped Isaac's Piano.","Isaac explains to Katherine his iceberg idea"],
        ["The Metropolis Post - Edition 3","metropost_3.svg","November 17, 2019","Every sunday! (Or early monday)","The third edition of The Metropolis Post"],
        ["Iceberg part 2","iceberg_2.svg","November 18, 2019","These are just fillers. Don't worry... Isaacs piano comes into this eventually.","Isaac talks to seymour about his iceberg ideas"],
        ["Iceberg part 3","iceberg_3.svg","November 19, 2019","8 days to thanksgiving!","The icebergs start coming in"],
        ["Sheeple","sheeple.svg","November 20, 2019","Yes, I am calling anyone who <em>STILL</em> thinks global warming is a myth a sheeple.","Isaac and Katherine meet a herd of sheeple"],
        ["Iceberg part 4","iceberg_4.svg","November 21, 2019","The extra guy is Isaac's twin brother, who I haven't run for a very long time.","Seymour calculates everyones weight"],
        ["Iceberg part 5","iceberg_5.svg","November 22, 2019","Someone remind me to make a Thanksgiving 2019 series before its too late...","Katherine yells at Isaac for forgetting Stevenson and Isaac"],
        ["Thanksgiving 2019 part 1","thanksgiving_2019_1.svg","November 23, 2019","I probably won't do an animated one for some time.","Harold gets knocked over by a really angry turkey"],
        ["Thanksgiving 2019 part 2","thanksgiving_2019_2.svg","November 24, 2019","This is turning into a theme.","Isaac gets knocked over by a really angry turkey"],
        ["Thanksgiving 2019 part 3","thanksgiving_2019_3.svg","November 25, 2019","I suppose the Thanksgiving 2019 series is just a compilation of misadventures.","Isaac and Katherine distract a character referencing Lucy (from Peanuts)"],
        ["Thanksgiving 2019 part 4","thanksgiving_2019_4.svg","November 26, 2019","The piano!","The angry turkey knocks over Isaac again"],
        ["Iceberg part 6","iceberg_6.svg","November 27, 2019","More iceberg! I guess <i>animated</i> comics will soon be rare, instead of the vice versa.","The iceberg floats through Venice"],
        ["Iceberg part 7","iceberg_7.svg","November 30, 3019","Its almost Christmas! I guess it's time to deck out my comic with Christmas scenes","Seymour and Katherine play checkers"],
        ["Christmas present","christmas_present.svg","December 1, 2019","A present! The first christmas image!","An image of a christmas present"],
        ["Iceberg part 8", "iceberg_8.svg","December 3, 2019","The advent calendar is coming soon!","Isaac tries to get Nigel to listen to him"],
        ["Iceberg part 9", "iceberg_9.svg","December 4, 2019","This is <strong>not</strong> a copy of the Inflatable Mattress series.","A whale comes up to the Iceberg"],
        ["Iceberg part 10","iceberg_10.svg","December 5, 2019","Eventually the advent calendar will be finished. At the time of writing, I have made 6 of the ornaments! (Lots of detail)","(broken comic) Seymour, Katherine, and Isaac (respectively) worry about the whale"],
        ["Iceberg part 11","iceberg_11.svg","December 6, 2019","Sorry for the unfinished comic yesterday. I guess I got absent minded?","Isaac finds a nice cave to play his piano in"],
        ["Stu Brunswickson part 1","stu_brunswickson_1.svg","December 8, 2019","Ouch.","Isaac strangely gets locked in the ring with Stu Brunswickson"],
        ["Advent Calendar","advent_calendar.svg","December 9, 2019","The long awaited advent calendar! Until the 25th, I will probably post <i>behind</i> the calendar, so you have to go back one to see the recent comics. New ornaments pop up every day.","The advent calendar"],
        ["Stu Brunswickson part 2","stu_brunswickson_2.svg","December 22, 2020","Sorry about the missed comics. My site was (and, at the moment, is) under renovation and at the time of writing I just got it working at the most basic functionality.","Isaac finds Seymour in the ring as well"],
        ["Stu Brunswickson part 3","stu_brunswickson_3.svg","January 7, 2020","I'm sorry, you say your looking for a place called Stu Brunswickson?","Seymour confuses Isaac more"],
        ["Stu Brunswickson part 4","stu_brunswickson_4.svg","January 9, 2020","Bad Seymour. Go sit in a corner. Your such a cute wittle Seymour.","It is clarified how they got in the ring"],
        ["World Domination part 1","world_domination_1.svg","January 10, 2020","For people with small screens, the text on his robe is 'Ponies'","Katherine tries to get Isaac out of bed"],
        ["World Domination part 2","world_domination_2.svg","January 11, 2020","And lets not even mention the pop-up ads...","Isaac learns about the Microsoft Zombies"],
        ["World Domination part 3","world_domination_3.svg","January 12, 2020","More obscure humor from LinuxRocks2000! (The name is actually growing on me)","Isaac learns about the Microsoft Lackeys"],
        ["World Domination part 4","world_domination_4.svg","January 18, 2020","Constance the loud, patronizing weirdo","Isaac meets Constance"],
        ["World Domination part 5","world_domination_5.svg","January 22, 2020","Is upshutted a word? I think it would apply here...","Isaac presses Katherine for information and gets upshutted by Constance"]
    ]
}
