#!/usr/bin/env python3

import git
print("Pushing git")
repo=git.Repo(r"/home/awesome/desk/programs/web-based/github-pages/LinuxRocks2000.github.io")
try:
    repo.git.add(A=True)
    repo.index.commit("Updating my webcomic from an automated build helper I scripted in python")
    origin=repo.remote(name="origin")
    origin.push()
except git.GitCommandError as G:
    print("Invalid password. Please try again.")
    try:
        origin=repo.remote(name="origin")
        origin.push()
    except git.GitCommandError as G:
        print("Two strikes... YOUR OUT")
